#!/bin/bash

# Exit on errors
set -e

# Start setting up KNIT vars
KNIT_REPO=${KNIT_REPO:-shakefu}

# Build the base image
docker built -t "$KNIT_REPO/yarn-knit:base" -f base/Dockerfile base/

# Build the onbuild image
docker built -t "$KNIT_REPO/yarn-knit:onbuild" -f onbuild/Dockerfile onbuild/

